# serverless.yml
service: miller-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: beta
  region: us-east-1
  timeout: 15 # optional, in seconds, default is 6

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'